services:
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: Users.API/Dockerfile
      
  users.db:
    image: postgres:latest
    volumes:
      - users-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    depends_on:
      postgres-keycloak:
        condition: service_healthy
  
  postgres-keycloak:
    image: postgres:latest
    volumes:
      - keycloak-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  users-pgdata:
  keycloak-pgdata: